# Generated by Django 5.2.1 on 2025-07-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('Coral Reef Protection', 'Coral Reef Protection'), ('Sea Turtle Conservation', 'Sea Turtle Conservation'), ('Ocean Cleanup Initiative', 'Ocean Cleanup Initiative'), ('Marine Research Fund', 'Marine Research Fund')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('description', models.TextField()),
                ('impact', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
