# Generated by Django 5.2.4 on 2025-07-22 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('coral-reef', 'Coral Reef Protection'), ('sea-turtle', 'Sea Turtle Conservation'), ('ocean-cleanup', 'Ocean Cleanup Initiative'), ('marine-research', 'Marine Research Fund')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('apple', 'Apple Pay'), ('google', 'Google Pay')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
