# Generated by Django 5.2.1 on 2025-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('apple', 'Apple Pay'), ('google', 'Google Pay')], default='card', max_length=20),
            preserve_default=False,
        ),
    ]
