# Generated by Django 5.2.1 on 2025-07-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='impact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='scheme',
            field=models.CharField(choices=[('coral-reef', 'Coral Reef Protection'), ('sea-turtle', 'Sea Turtle Conservation'), ('ocean-cleanup', 'Ocean Cleanup Initiative'), ('marine-research', 'Marine Research Fund')], max_length=100),
        ),
    ]
