# Generated by Django 5.2.1 on 2025-07-19 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=150)),
                ('marine_character', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('online', 'Online'), ('recently', 'Recently Active'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('last_seen', models.CharField(default='unknown', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
