# Generated by Django 5.2.4 on 2025-07-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('Experiences', 'Experiences'), ('Conservation', 'Conservation'), ('Photography', 'Photography'), ('Discussion', 'Discussion')], default='Discussion', max_length=50),
        ),
    ]
