# Generated by Django 5.2.1 on 2025-08-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_achievement_activity_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='redemption_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_points_spent',
            field=models.IntegerField(default=0),
        ),
    ]
